name: Bug Report
description: A report about an issue, crash or similar.
title: "[Issue]: "
labels: ["issue"]
assignees:
  - Gbergz
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A short explanation of what happened.
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: packversion
    attributes:
      label: Pack Version
      description: Put the pack version you are currently on here.
      value: "Version: "
  - type: textarea
    id: repro
    attributes:
      label: To Reproduce
      description: Steps to reproduce the issue/error/crash, (steps can be edited)..
      value: "1."
  - type: checkboxes
    id: addedmods
    attributes:
      label: Are you using Shaders?
      options:
        - label: Yes. I have activated shaders.
        - label: No. Shaders are inactive.
    validations:
      required: true
  - type: checkboxes
    id: server
    attributes:
      label: Are you on a Server?
      options:
        - label: Yes.
        - label: No.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: whole latest.log output & crash report.
      description: Please copy and paste the whole latest.log output & crash report to a paste site like https://gist.github.com/ or similar.
      render: shell
  - type: textarea
    id: anythingelse
    attributes:
      label: Anything else to add?
      description: Optional.
